### ISSUE TITLE
python2 / python3 - Common role on Ubuntu 18.04. fails

### ISSUE THREAD

**Issue by BigPii** [osism/documentation#111]
Hi,

I'm kinda new to this ecosystem, so excuse me if I'm missing something.

For me the changes made in osism/ansible-docker#55 lead into an error when deploying the kolla common role on Ubuntu 18.04.
I think kolla-ansible:train still uses python2 and therefore runs into an error when trying to manage docker resources on the destination hosts.
Well I guess kolla-ansible doesn't explicitly choose to use python2, but rather it's the default python interpreter on Ubuntu 18.04.
I assume this would work if python3 was set as default python interpreter on the destination host - but it isn't and I don't think it's done during bootstrapping.

best regards,
Patrick

**Comment by berendt** [comment]
Closing old and no longer relevant issues.
