### ISSUE TITLE
wrong location for ceph.client.glance.keyring

### ISSUE THREAD

**Issue by maliblatt** [osism/documentation#130]
from documentation the keyring has to go to environments/kolla/files/overlays/glance-api/ceph.client.glance.keyring.
when deploying glance with 'osism-kolla deploy glance' I get:
"Could not find or access '/opt/configuration/environments/kolla/files/overlays/glance/ceph.client.glance.keyring' on the Ansible Controller."

**Comment by grawert** [comment]
That is going to be fixed in #142
