### ISSUE TITLE
Documentation: Change grub settings usage

### ISSUE THREAD

**Issue by matfechner** [osism/documentation#358]
Documentation: Change grub settings usage

Links inside https://docs.osism.tech/configuration/environments/generic/grub.html are out of reach
because  procedure changed:

https://docs.debops.org/en/master/ansible/roles/grub/defaults/main.html#grub-configuration-options

**Comment by muellerbe** [comment]
host_vars/group_vars
grub__default_configuration:
  - name: 'cmdline_linux_default'
    value:
      - iommu=pt
      - iommu=1
osism-generic grub

**Comment by osfrickler** [comment]
https://github.com/osism/documentation/pull/363
