### ISSUE TITLE
Ansible style guide: The need of exceptions for ansible-lint

### ISSUE THREAD

**Issue by ra-rau** [osism/documentation#373]
In some cases there is a need to use ansible modules that are not listed in the ansible galaxy. For exampel the osism modules or scan_services (https://github.com/ansible/awx-facts-playbooks) etc. In this cases we will need an exception for the ansible-lint. For the future it could be better to write the exception directly after writing the code. So we wont forget it anymore.

**Comment by berendt** [comment]
I think the right approach at this point would not be to use an exception but to use mocks. This means that the role or module does not actually have to be present and the parts that need these roles or modules do not have to be excluded. This works both with roles and with modules.

Sample from https://github.com/ansible/ansible-lint/blob/main/.ansible-lint.

```
# Mock modules or roles in order to pass ansible-playbook --syntax-check
mock_modules:
  - zuul_return
  # note the foo.bar is invalid as being neither a module or a collection
  - fake_namespace.fake_collection.fake_module
  - fake_namespace.fake_collection.fake_module.fake_submodule
mock_roles:
  - mocked_role
  - author.role_name # old standalone galaxy role
  - fake_namespace.fake_collection.fake_role # role within a collection
```
