### ISSUE TITLE
New design breaks table in overview/requirements

### ISSUE THREAD

**Issue by DavidRabel-b1** [osism/documentation#38]
New design breaks table in overview/requirements

The columns "optional" and "routed" are displayed as completely empty now.

**Comment by berendt** [comment]
Looks like the sphinx_fontawesome plugin is broken with the new alabaster theme.

**Comment by muellerbe** [comment]
looks good at the moment, could this be closed?

**Comment by muellerbe** [comment]
moved with commit d500501993162218264dded8d21cc31460b97ffc
in new file overview/networks.rst it looks good
