### ISSUE TITLE
How to enable mitogen

### ISSUE THREAD

**Issue by berendt** [osism/documentation#40]

**Comment by muellerbe** [comment]
git clone https://github.com/dw/mitogen.git

ansible.cfg
[defaults]
strategy_plugins = ~/git/seuf/mitogen/ansible_mitogen/plugins/strategy
strategy = mitogen_linear

or
pip install mitogen

ansible.cfg
[defaults]
strategy_plugins = /usr/lib/python2.7/site-packages/ansible_mitogen/plugins/strategy
strategy = mitogen_linear

**Comment by muellerbe** [comment]
https://aperogeek.fr/ansible-mitogen/

https://dev.to/sshnaidm/speed-up-ansible-with-mitogen-2c3j

**Comment by berendt** [comment]
No longer relevant. Mitogen plugins have been removed.
