### ISSUE TITLE
Incorrect documentation to change certificate in Haproxy

### ISSUE THREAD

**Issue by zach-b1** [osism/documentation#443]
The documentation under "https://docs.osism.tech/services/haproxy.html#change-certificate" don't work (after Train) and is complete different to https://docs.osism.tech/configuration/environments/openstack.html#id1

**Comment by berendt** [comment]
@zach-b1 Are you going to revise it accordingly?

**Comment by zach-b1** [comment]
yes, please see the merge request:
https://github.com/osism/documentation/pull/445

**Comment by berendt** [comment]
Closed with c6a013fc59dc1a4dd5a65229ffc519bb4f6f5819
