### ISSUE TITLE
cookiecutter links do not work

### ISSUE THREAD

**Issue by muellerbe** [osism/documentation#86]
the links do not work in perparation section of the following link
http://docs.osism.io/upgrade/kolla.html

**Comment by berendt** [comment]
now works

**Comment by muellerbe** [comment]
no, not all links work, there is only one haproxy.cfg.rocky present
https://github.com/osism/cfg-cookiecutter/tree/master/cfg-%7B%7Bcookiecutter.project_name%7D%7D/environments/kolla/files/overlays/haproxy
can we link or describe the way for finding the files in 
https://git.betacloud-solutions.de/generic/cookiecutter

**Comment by berendt** [comment]
I add the Queens file to the cookie cutter.

https://git.betacloud-solutions.de/generic/cookiecutter is deprecated. New repository is https://github.com/osism/cfg-cookiecutter.

**Comment by muellerbe** [comment]
ok, thanks for the information. So, I will close this issue.
